apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxdemos
  name: nginxdemo-svc
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginxdemos
  type: NodePort
status:
  loadBalancer: {}
